name: ai_friend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 
  http: ^1.2.1
  dio: ^5.4.2+1
  cupertino_icons: ^1.0.2
  uuid: ^4.3.3
  chat_gpt_sdk: ^3.0.4
  get_it: ^7.6.7
  provider: ^6.1.2
  rxdart: ^0.27.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg:
  # firebase
  firebase_core: ^2.27.2
  firebase_storage: ^11.6.11
  firebase_analytics: ^10.10.7
  firebase_messaging: ^14.7.21
  firebase_remote_config: ^4.3.4
  # video
  flick_video_player: ^0.7.0
  video_player: ^2.8.4
  audioplayers: ^6.0.0
  progressive_image: ^2.0.1
  flutter_acrylic: ^1.1.3
  flutter_layout_grid: ^2.0.6
  bounce: ^1.0.2
  contained_tab_bar_view: ^0.8.0
  path_provider: ^2.1.3
  swipe_image_gallery: ^0.8.3
  animations: ^2.0.11
  lottie: ^3.1.0
  # hero_animation: ^1.1.4
  proste_route_animation: ^2.0.2
  pro_animated_blur: ^0.0.2+1
  page_route_animator: ^1.0.4
  scroll_datetime_picker: 
  shimmer_animation: ^2.1.0
  flutter_animate: ^0.3.0+1
  rate_my_app: ^1.1.3
  image_gallery_saver: ^2.0.3
  share_plus:
  url_launcher: ^6.2.6
  apphud: ^2.5.0
  flutter_native_splash: ^2.3.8
  oktoast: ^3.4.0
  # facebook_app_events: ^0.19.2
  singular_flutter_sdk: ^1.4.0
  onesignal_flutter: ^5.2.0
  app_tracking_transparency: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.4.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/paywall/
    - assets/colored_icons/
    - assets/icons/
    - assets/intro_videos/
    - assets/alice_photos/
    - assets/new_message.mp3
    - assets/lottie_loader.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # example:
  fonts:
    - family: SFPro
      fonts:
        - asset: fonts/SFProText-Regular.ttf
    - family: GothamPro
      fonts:
        - asset: fonts/GothamProRegular.ttf
        - asset: fonts/GothamProBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# Gen
flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
    flare_flutter: false

flutter_native_splash:
  background_image: "assets/images/splash_bg.jpg"
  image: "assets/images/splash_icon.png"
  branding_mode: center
  color: "#22133A"
  fullscreen: true
  ios: true
  android: false
  web: false