// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjJ2EKxrSTfbJ6g8qOMW1Myyim4JjkcM0',
    appId: '1:764870781383:web:a41ed62cad7f58ab23d1e2',
    messagingSenderId: '764870781383',
    projectId: 'aifriend-aebb3',
    authDomain: 'aifriend-aebb3.firebaseapp.com',
    storageBucket: 'aifriend-aebb3.appspot.com',
    measurementId: 'G-67SZ1D5DG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgOCXhXK73Yr9TVJ_7lI-EzRPnSilgCbQ',
    appId: '1:764870781383:android:abb75e9dc97e8edf23d1e2',
    messagingSenderId: '764870781383',
    projectId: 'aifriend-aebb3',
    storageBucket: 'aifriend-aebb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU072T-v4xjGiriF6ornZCXo5TlBKU5RU',
    appId: '1:764870781383:ios:fc52d4629fc0f51623d1e2',
    messagingSenderId: '764870781383',
    projectId: 'aifriend-aebb3',
    storageBucket: 'aifriend-aebb3.appspot.com',
    iosBundleId: 'aifriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU072T-v4xjGiriF6ornZCXo5TlBKU5RU',
    appId: '1:764870781383:ios:d52691fce7f3a78023d1e2',
    messagingSenderId: '764870781383',
    projectId: 'aifriend-aebb3',
    storageBucket: 'aifriend-aebb3.appspot.com',
    iosBundleId: 'com.example.aiFriend.RunnerTests',
  );
}
